# Generated by Django 4.2.7 on 2023-11-06 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerhans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_type', models.IntegerField(choices=[(1, 'Стальная'), (2, 'Иск.камень')], help_text='Вид товара', verbose_name='Назначение')),
                ('foto', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('article', models.CharField(help_text='Артикул', max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(help_text='Цена', verbose_name='Цена')),
                ('text_about_item', models.TextField(help_text='О товаре', max_length=200, verbose_name='Краткое описание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия и имя', max_length=30, verbose_name='Заводчик')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон')),
                ('article', models.CharField(help_text='Артикул', max_length=20, verbose_name='Артикул')),
                ('message', models.TextField(help_text='Замечания', max_length=100, verbose_name='Замечания')),
                ('order_data', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Gardeneqm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_type', models.IntegerField(choices=[(1, 'Ерш'), (2, 'Полка')], help_text='Вид товара', verbose_name='Назначение')),
                ('foto', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('article', models.CharField(help_text='Артикул', max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(help_text='Цена', verbose_name='Цена')),
                ('text_about_item', models.TextField(help_text='О товаре', max_length=200, verbose_name='Краткое описание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
