# Generated by Django 4.2.7 on 2023-11-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerhans', '0002_accessories_basket_gardeneqm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sewerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_type', models.IntegerField(choices=[(1, 'Ерш'), (2, 'Полка')], help_text='Вид товара', verbose_name='Назначение')),
                ('foto', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('article', models.CharField(help_text='Артикул', max_length=20, verbose_name='Артикул')),
                ('price', models.IntegerField(help_text='Цена', verbose_name='Цена')),
                ('text_about_item', models.TextField(help_text='О товаре', max_length=200, verbose_name='Краткое описание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
