# Generated by Django 4.1.5 on 2023-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_id', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HomePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.IntegerField(choices=[(1, 'Собака'), (2, 'Кот'), (3, 'Птица'), (4, 'Насекомое')], help_text='Вид питомца', verbose_name='Категория')),
                ('foto', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('name_pets', models.CharField(help_text='Кличка', max_length=20, verbose_name='Кличка')),
                ('age_pets', models.IntegerField(help_text='Возраст', verbose_name='Возвраст')),
                ('text_about_pets', models.TextField(help_text='Замечания', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets', models.CharField(help_text='Enter field documentation', max_length=20)),
                ('text_news', models.TextField(help_text='Enter field documentation', max_length=20)),
                ('data', models.DateTimeField(blank=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=20)),
                ('help_type', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия и имя', max_length=30)),
                ('phone', models.CharField(help_text='Номер телефона', max_length=10)),
                ('pets', models.CharField(help_text='Питомец', max_length=20)),
                ('message', models.TextField(help_text='Замечания', max_length=100)),
                ('data_order_pet', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPetTemporarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Фамилия и имя', max_length=30)),
                ('phone', models.CharField(help_text='Номер телефона', max_length=10)),
                ('pets', models.CharField(help_text='Питомец', max_length=20)),
                ('data_order_pet', models.DateTimeField(verbose_name='Дата')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_tame', models.DateTimeField(verbose_name='Окончание')),
                ('message', models.TextField(help_text='Замечания', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(help_text='Инициалы', max_length=30)),
                ('phone_numb', models.CharField(help_text='Телефон', max_length=10)),
                ('transport_type', models.PositiveSmallIntegerField(choices=[(1, 'Доставка еды, медикаментов и других небольших вещей'), (2, 'Доставка сена или соломы, строительных материлов для будок и других крупногабаритных вещей'), (3, 'Транспортировка небольших собак и котов'), (4, 'Транспортировка больших собак')], editable=False, null=True)),
                ('data_order_pet', models.DateTimeField(verbose_name='Дата')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_tame', models.DateTimeField(verbose_name='Окончание')),
                ('message', models.TextField(help_text='Замечания', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VolOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vol', models.CharField(help_text='Фамилия и имя', max_length=30)),
                ('phone', models.CharField(help_text='Номер телефона', max_length=10)),
                ('vol_type', models.PositiveSmallIntegerField(choices=[(1, 'Хочу помогать на постоянной основе(расписание можно подобрать так, как будет вам удобно'), (2, 'Готов помогать иногда.Хочу выбрать удобное для меня время')], editable=False, null=True, verbose_name='vol_type')),
                ('data_order_pet', models.DateTimeField(verbose_name='Дата')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('message', models.CharField(help_text='Замечания', max_length=100)),
            ],
        ),
    ]
