# Generated by Django 4.1.5 on 2023-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pets',
        ),
        migrations.AddField(
            model_name='news',
            name='foto',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
