# Generated by Django 4.1.5 on 2023-01-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpettemporarity',
            old_name='end_tame',
            new_name='end_time',
        ),
    ]
