# Generated by Django 4.1.5 on 2023-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0002_remove_news_pets_news_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_news',
            field=models.TextField(help_text='Enter field documentation', max_length=250),
        ),
    ]
