# Generated by Django 4.1.5 on 2023-02-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0003_alter_news_text_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepet',
            options={'verbose_name': 'Питомцы'},
        ),
    ]
