# Generated by Django 4.1.5 on 2023-01-16 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0003_alter_orderpet_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhelp',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='transportationorder',
            name='phone_numb',
        ),
        migrations.AddField(
            model_name='orderhelp',
            name='phone',
            field=models.CharField(default=2, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='phone',
            field=models.CharField(default=2, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpettemporarity',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='volorder',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
