# Generated by Django 4.1.5 on 2023-01-16 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0004_remove_orderhelp_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpet',
            old_name='data_order_pet',
            new_name='order_data',
        ),
        migrations.RenameField(
            model_name='orderpettemporarity',
            old_name='data_order_pet',
            new_name='order_data',
        ),
        migrations.AlterField(
            model_name='homepet',
            name='text_about_pets',
            field=models.TextField(help_text='Замечания', max_length=200, verbose_name='Кратко о питомце'),
        ),
        migrations.AlterField(
            model_name='orderpettemporarity',
            name='message',
            field=models.TextField(help_text='Замечания', max_length=100, verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='orderpettemporarity',
            name='name',
            field=models.CharField(help_text='Фамилия и имя', max_length=30, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='orderpettemporarity',
            name='pets',
            field=models.CharField(help_text='Питомец', max_length=20, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='orderpettemporarity',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон'),
        ),
    ]
