# Generated by Django 4.1.5 on 2023-01-16 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0005_rename_data_order_pet_orderpet_order_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationorder',
            old_name='data_order_pet',
            new_name='order_data',
        ),
        migrations.RemoveField(
            model_name='transportationorder',
            name='end_tame',
        ),
        migrations.RemoveField(
            model_name='transportationorder',
            name='start_time',
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='end_point',
            field=models.CharField(default=2, max_length=30, verbose_name='Выгрузить'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportationorder',
            name='start_point',
            field=models.CharField(default=2, max_length=30, verbose_name='Погрузить'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderhelp',
            name='name',
            field=models.CharField(help_text='Имя', max_length=20, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='orderhelp',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='orderpet',
            name='message',
            field=models.TextField(help_text='Замечания', max_length=100, verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='orderpet',
            name='name',
            field=models.CharField(help_text='Фамилия и имя', max_length=30, verbose_name='Заводчик'),
        ),
        migrations.AlterField(
            model_name='orderpet',
            name='pets',
            field=models.CharField(help_text='Питомец', max_length=20, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='orderpet',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='driver_name',
            field=models.CharField(help_text='Инициалы', max_length=30, verbose_name='Перевозчик'),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='message',
            field=models.TextField(help_text='Замечания', max_length=100, verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон'),
        ),
    ]
