# Generated by Django 4.1.5 on 2023-01-17 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0006_rename_data_order_pet_transportationorder_order_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForageAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forage_type', models.IntegerField(choices=[(1, 'крупы'), (2, 'Сухие корма'), (3, 'Влажные корма'), (4, 'Фарш для собак')], editable=False, null=True, verbose_name='Вид корма')),
                ('forage_weight', models.IntegerField()),
                ('name', models.CharField(help_text='Фамилия и имя', max_length=30, verbose_name='Волонтер')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.IntegerField(choices=[(1, 'Ошейники, поводки, намордники'), (2, 'Опилки и солома'), (3, 'Посуда'), (4, 'Теплые вещи'), (5, 'Будки')], null=True, verbose_name='Категория')),
                ('item_qty', models.IntegerField()),
                ('which_item', models.CharField(help_text='Замечания', max_length=100, verbose_name='Вещь')),
                ('name', models.CharField(help_text='Фамилия и имя', max_length=30, verbose_name='Волонтер')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentosAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_type', models.IntegerField(choices=[(1, 'цефтриаксон'), (2, 'новокаин'), (3, 'гискан'), (4, 'гамавит'), (5, 'катозал'), (6, 'антитокс'), (7, 'фоспренил'), (8, 'энтеросгель'), (9, 'препараты от глистов'), (10, 'препараты от блох,клещей'), (11, 'для заживления ран')], verbose_name='Препарат')),
                ('med_weight', models.IntegerField()),
                ('name', models.CharField(help_text='Фамилия и имя', max_length=30, verbose_name='Волонтер')),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон')),
            ],
        ),
        migrations.RenameField(
            model_name='volorder',
            old_name='data_order_pet',
            new_name='data_order',
        ),
        migrations.AlterField(
            model_name='orderpettemporarity',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='transportationorder',
            name='transport_type',
            field=models.IntegerField(choices=[(1, 'Доставка еды, медикаментов и других небольших вещей'), (2, 'Доставка сена или соломы, строительных материлов для будок и других крупногабаритных вещей'), (3, 'Транспортировка небольших собак и котов'), (4, 'Транспортировка больших собак')], null=True, verbose_name='Вид перевозки'),
        ),
        migrations.AlterField(
            model_name='volorder',
            name='name_vol',
            field=models.CharField(help_text='Фамилия и имя', max_length=30, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='volorder',
            name='vol_type',
            field=models.IntegerField(choices=[(1, 'Хочу помогать на постоянной основе(расписание можно подобрать так, как будет вам удобно'), (2, 'Готов помогать иногда.Хочу выбрать удобное для меня время')], null=True, verbose_name='vol_type'),
        ),
    ]
