# Generated by Django 4.2.6 on 2023-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_pets', '0008_alter_forageadd_phone_alter_itemadd_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forageadd',
            name='forage_type',
            field=models.IntegerField(choices=[(1, 'крупы'), (2, 'Сухие корма'), (3, 'Влажные корма'), (4, 'Фарш для собак')], null=True, verbose_name='Вид корма'),
        ),
        migrations.AlterField(
            model_name='homepet',
            name='age_pets',
            field=models.IntegerField(help_text='Возраст', verbose_name='Возраст'),
        ),
    ]
